#! /bin/sh

# monthly dump of ldap data

if [ `id -u` != 0 ]
then
  echo "You must have root privilege to run this program."
  exit 1
fi

# assumes ldap admin password stored in this file
LDAPPASSFILE=/root/ldappasswd

# put ldif backup file here
BACKDIR=/root/ldapbackups

# ldap info
LDAPCN="cn=admin,dc=cs,dc=college,dc=edu"
LDAPBASE="dc=cs,dc=college,dc=edu" 
LDAPURL="ldaps://ldap.cs.college.edu"

# check for/make dir
if [ ! -d $BACKDIR ] ; then
  mkdir $BACKDIR
  chmod 700 $BACKDIR
fi

# unique file name
d=`date +'%m%d%Y'`
fn=ldap_dump-${d}.ldif

# make the backup
cd $BACKDIR
ldapsearch -Wx -D $LDAPCN -y $LDAPPASSFILE -b $LDAPBASE -H $LDAPURL -LLL > $fn
